# Generated by Django 4.2.26 on 2025-12-02 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("consulting", "Consulting"),
                            ("product_management", "Product Management"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(help_text="The main case prompt/question")),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context and background information",
                    ),
                ),
                (
                    "exhibits",
                    models.JSONField(
                        default=list,
                        help_text="List of exhibits (tables, charts, data) for the case",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cases",
                "ordering": ["-created_at"],
            },
        ),
    ]
