# Generated by Django 4.2.26 on 2025-12-02 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(help_text="Overall feedback summary")),
                (
                    "strengths",
                    models.JSONField(
                        default=list, help_text="List of identified strengths"
                    ),
                ),
                (
                    "areas_for_improvement",
                    models.JSONField(
                        default=list, help_text="List of areas that need improvement"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Specific recommendations and drills"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="analysis.evaluation",
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
