# Generated by Django 4.2.26 on 2025-12-02 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="recordings/%Y/%m/%d/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("video", "Video"), ("audio", "Audio")], max_length=10
                    ),
                ),
                ("transcription", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "recordings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("structure_score", models.IntegerField(default=0)),
                ("hypothesis_score", models.IntegerField(default=0)),
                ("math_score", models.IntegerField(default=0)),
                ("insight_score", models.IntegerField(default=0)),
                ("body_language_score", models.IntegerField(default=0)),
                ("speech_pacing_score", models.IntegerField(default=0)),
                ("presence_score", models.IntegerField(default=0)),
                ("delivery_clarity_score", models.IntegerField(default=0)),
                ("overall_score", models.IntegerField(default=0)),
                ("content_analysis", models.JSONField(default=dict)),
                ("communication_analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "evaluations",
                "ordering": ["-created_at"],
            },
        ),
    ]
