# Generated by Django 4.2.27 on 2025-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("framework", "Framework"),
                    ("data_analysis", "Data Analysis"),
                    ("recommendation", "Recommendation"),
                    ("pushback", "Pushback"),
                    ("conclusion", "Conclusion"),
                    ("completed", "Completed"),
                ],
                default="framework",
                max_length=50,
            ),
        ),
    ]
